version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb_data: